name: Publish processes (Windows) to Pages
on: workflow_dispatch
permissions: { pages: write, id-token: write, contents: write }

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate HTML
        shell: pwsh
        run: |
          New-Item -Type Directory -Force site
          $ctz   = [TimeZoneInfo]::FindSystemTimeZoneById('Central Standard Time')
          $nowCT = [TimeZoneInfo]::ConvertTime([DateTime]::UtcNow, $ctz)
          $abbr  = $ctz.IsDaylightSavingTime($nowCT) ? 'CDT' : 'CST'
          $stamp = $nowCT.ToString('MMddyy:HHmmss') + " $abbr"
          Get-Process | Sort-Object WorkingSet64 -Descending | Select-Object -First 20 ProcessName, Id, CPU, WS |
            ConvertTo-Html -As Table -Title 'Processes' -PreContent "<h1>Processes (Windows runner)</h1><p>Updated $stamp</p>" |
            Set-Content site\WinProcesses.html -Encoding utf8

      - uses: actions/upload-pages-artifact@v3
        with: { path: site }

      # NEW: also commit the generated site/ back to the repo
      - name: Commit site/ to repo
        shell: pwsh
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add site/WinProcesses.html
          git commit -m "Update site (WinProcesses)" || echo "No changes"
          git push

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
